---
- name: ensure directory exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/v2ray
    - /etc/v2ray

- name: get v2ray binary package
  unarchive:
    src: "https://github.com/v2fly/v2ray-core/releases/download/v{{ app_ver }}/v2ray-linux-{{ app_arch }}.zip"
    dest: /opt/v2ray
    remote_src: yes

- name: symlink binary files
  file:
    src: "/opt/v2ray/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
  loop:
    - v2ray
    - v2ctl

- name: get uuid
  command: v2ctl uuid
  register: uuid
  changed_when: "uuid.rc != 0"

- name: generate v2ray config
  template:
    src: config.json.j2
    dest: /etc/v2ray/config.json
  notify:
    - restart v2ray

- name: copy systemd config
  copy:
    src: v2ray.service
    dest: /etc/systemd/system/v2ray.service

- name: enable v2ray service
  systemd:
    name: v2ray
    state: started
    daemon_reload: yes
    enabled: yes
